layout_spectrum: 0.8044776
typography_spectrum: 0.319939
color:
  saturation: 0.3848596
  lightness: 0.7088175
  brandStrength: 0.5398022
  rhythmicContrast: 0.3745989
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: Genolotse
